### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by bingweibi** [ricardonior29/easy_dialog#1]
When there is a textfield in the dialog, the keyboard pops up to block the dialog. How can I solve it?

**Comment by JavierDuarteC** [comment]
We have the same problem, but the dialog is not ment to have textfields in it, dialogs are used to inform or give options with buttons. So, you might need a new page for a form.

**Comment by digarahayu** [comment]
I hope you add position dialog like show dialog in top ,bottom or center
